### ISSUE TITLE
CameraException(error, register failed, the sensor listeners size has exceeded the maximum limit 128)

### ISSUE THREAD

**Issue by anamauad** [gabuldev/camera_camera#43]
While opening and closing the camera many times in the same day I'm getting the following error:

CameraException(error, register failed, the sensor listeners size has exceeded the maximum limit 128)

**Stack trace:**

#0 CameraController.initialize (package:camera/camera.dart:289)

#1 Subject.sink (package:rxdart/src/subjects/subject.dart)
#2 _CameraState.initState.. (package:camera_camera/page/camera.dart:57)

**Device parameters:**

brand: samsung
device: a31
hardware: mt6768
isPhysicalDevice: true
manufacturer: samsung
model: SM-A315G
versionCodename: REL
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01

**Comment by anamauad** [comment]
Maybe the camera is not unsubscribing its listeners when is closed, as described in
https://stackoverflow.com/questions/6919577/sensoreventlistener-doesnt-get-unregistered-with-unregisterlistener-method
