### ISSUE TITLE
Get error when take a picture and change to front camera on xperia Z

### ISSUE THREAD

**Issue by hungnv1709** [gabuldev/camera_camera#66]
i used camera_camera: ^2.0.2 on my source.
flutter doctor: 
`
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15 19A583 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)
`

- I get an error when take a picture by rear camera on xperia Z. 
`
E/libc    (10142): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (10142): Access denied finding property "vendor.camera.aux.packagelist"
E/flutter (10142): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: CameraException(captureTimeout, Picture capture request timed out)
E/flutter (10142): #0      CameraController.takePicture (package:camera/src/camera_controller.dart:346:7)
E/flutter (10142): <asynchronous suspension>
E/flutter (10142): #1      CameraCameraController.takePhoto (package:camera_camera/src/presentation/controller/camera_camera_controller.dart:145:18)
E/flutter (10142): <asynchronous suspension>
`
- And when i change to front camera, black screen appears.
logs: 
`E/flutter (10142): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference
E/flutter (10142): 	at io.flutter.plugins.camera.Camera.getMaxExposureOffset(Camera.java:928)
E/flutter (10142): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:193)
E/flutter (10142): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (10142): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (10142): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (10142): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10142): 	at android.os.MessageQueue.next(MessageQueue.java:376)
E/flutter (10142): 	at android.os.Looper.loop(Looper.java:244)
E/flutter (10142): 	at android.app.ActivityThread.main(ActivityThread.java:6706)
E/flutter (10142): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10142): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (10142): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (10142): )
E/flutter (10142): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (10142): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (10142): <asynchronous suspension>
E/flutter (10142): #2      MethodChannelCamera.getMaxExposureOffset (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:310:31)
E/flutter (10142): <asynchronous suspension>
E/flutter (10142): #3      CameraCameraController.init (package:camera_camera/src/presentation/controller/camera_camera_controller.dart:37:27)
`

**Comment by Tanelo** [comment]
Is it fixed ?
